### ISSUE TITLE
trian error

### ISSUE THREAD

**Issue by lfs119** [BioinfoMachineLearning/bio-diffusion#10]
![bio_diffusion](https://github.com/BioinfoMachineLearning/bio-diffusion/assets/23014201/c06e30e6-34b3-408b-bc17-2a43e7100045)

**Comment by amorehead** [comment]
Hi, @lfs119. Can you share which training command you were running when you encountered this issue?

**Comment by lfs119** [comment]
python3 src/train.py experiment=qm9_mol_gen_conditional_ddpm.yaml model.module_cfg.conditioning=[alpha]

**Comment by lfs119** [comment]
[Uploading train.log…]()

**Comment by lfs119** [comment]
![image](https://github.com/BioinfoMachineLearning/bio-diffusion/assets/23014201/c790d3e7-85ec-4229-9e25-e3283385892b)

**Comment by amorehead** [comment]
Hi, @lfs119. Thanks for forwarding this information to me. I believe I have identified and addressed the source of this issue. If you would, let me know if [this latest commit](https://github.com/BioinfoMachineLearning/bio-diffusion/commit/18f9d215da02b26712d8f96ef4a53557e395d6ac) fixes the issue on your end.

**Comment by lfs119** [comment]
Hi,@amorehead. I think the issue is fixed by your latest commit. Thanks for your support.
