### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by peonycabbage** [BioinfoMachineLearning/bio-diffusion#4]
Hello,I am highly interested in using this diffusion model with my custom dataset,  I am now trying to generate the .pkl files for my custom dataset. I understand that the default pkl files in this model are downloaded together with the dataset. Hence, I would like to ask if you have any guidelines on generating pkl files from scratch? Thank you very much and nice work on this model.

**Comment by amorehead** [comment]
Hello. I would be happy to help where I can. When you refer to `.pkl` files in the dataset, are you referring to the QM9 dataset's `QM9_smiles.pickle` file, or are you instead (or also) referring to QM9's e.g., `train.npz` data files?

In principle, these should be able to be built for arbitrary 3D molecular datasets, since they consist of the basics for this kind of diffusion model: 3D coordinates for each atom/residue/etc., possibly types of each atom/residue/etc, and (if available) chemical or physical properties associated with each atom/molecule.

**Comment by peonycabbage** [comment]
Hello, I am referring to smiles pickle file. I have already generated the .npz files. Maybe I can generate .pkl file from .npz files? Thank you for your swift reply.

**Comment by amorehead** [comment]
I believe this helper function for the QM9 dataset may be a useful reference for you. This function is borrowed from the original EDM codebase I believe: https://github.com/BioinfoMachineLearning/bio-diffusion/blob/dcef751d5e5fcc3e56018fa887c1089364efaafd/src/datamodules/components/edm/rdkit_functions.py#L32

Essentially, you only need to run this function once for each dataset to store a `{dataset_name}_smiles.pickle` file on your local disk for future loading at runtime/train time. It should be feasible to adapt this function to work with custom datasets, assuming they are based on small molecules.

**Comment by amorehead** [comment]
Essentially, you only need to run this function once for each dataset to store a `{dataset_name}_smiles.pickle` file on your local disk for future loading at runtime/train time.

**Comment by peonycabbage** [comment]
Thank you @amorehead  for the guidance. I will try to adapt it to my custom dataset but before running that function, I believe I need to define my "num_nodes" first

**Comment by amorehead** [comment]
Happy to help. If I recall correctly, `num_nodes` (in the context of EDM dataloading source code) refers to (what I call) a `node_mask` of shape [num_nodes], where each entry in this tensor/array is a boolean value of `True` of the atom is present and `False` if it is missing. You'll probably want to double-check me on this though, as it's been a while since I last looked at this bit of logic.

**Comment by peonycabbage** [comment]
Thank you @amorehead. I am now processing the xyz files, and I am getting this error:

`File "/mnt/d/Project2/bio-diffusion/src/datamodules/components/edm/process.py", line 110, in process_xyz_files
    with readfile(file) as openfile:
AttributeError: __enter__`


I tried to import `contextlib` and added @contextlib.contextmanager before `def readfile(data_pt):` however, I am getting this error: `TypeError: 'NoneType' object is not an iterator`

I am not sure if this is relevant but my custom dataset is in .cif file format and I have converted them to .xyz using a python script

**Comment by amorehead** [comment]
Hi, @peonycabbage. Unfortunately, I have not worked with `.cif` file extensions much at all, so I cannot give you direct advise on how to address this error. However, I can point you to the repository from which this `process` script originated: https://github.com/ehoogeboom/e3_diffusion_for_molecules/blob/fce07d701a2d2340f3522df588832c2c0f7e044a/qm9/data/prepare/process.py#L36

I hope this reference gives you some clues as to what is going wrong in data processing here. Let me know if I can help in any other way.

**Comment by peonycabbage** [comment]
Hello @amorehead, I hope you're doing well. I wanted to update you on my progress and ask for some clarification regarding some functions in the .qm9 file. Specifically, I'm trying to generate a dictionary for my target, which is already known since it has a column in my .csv file.

I've been working on refactoring the function called "get_thermo_dict," but I'm a bit confused about the parameter it returns. The function "add_thermo_targets" has a parameter called "therm_energy_dict," and I'm wondering if it's the same as the "therm_energy" parameter that "get_thermo_dict" returns.

Given that my targets are already known, I'm thinking that I may not need to use the "get_unique_charges" function. I would appreciate any insights/guidance. Thank you very much.

**Comment by amorehead** [comment]
Hi, @peonycabbage. Apologies for my delayed response as I have a few other deadlines I am currently working towards. A few thoughts I had:

- As you mentioned the `get_thermo_dict` function, I assume you are trying to process a new dataset comprised of new molecular properties for each 3D molecule in your dataset (e.g., properties that are not exactly contained in QM9). If that's the case, then yes, I believe you can simply pass the `add_thermo_targets` function the `thermo_energy` object that `get_thermo_dict` returns for each dataset split (e.g., `train`, `valid`, etc). You will want to double-check that the energies being used here are applicable to your use case (I cannot advise in this regard).
- Without knowing exactly what type of molecular data you are trying to adapt the dataset processing scripts for, I won't be able to provide much guidance on your question about `charges`. In QM9, scalar charges are provided for each atom, so we can train our model to generate these charges in addition to positioning the atoms in 3D space and assigning them a discrete atom type. In your case, I am not sure if you have access to these charges (or can empirically assign them to each atom).

**Comment by amorehead** [comment]
Hi, @peonycabbage.

If you have any other questions arise, please feel free to let me know in a separate issue. For the time being, I will be closing this issue due to nonactivity.

Best,
Alex

**Comment by yiyanliao** [comment]
Hey @amorehead , I am doing the exact same thing, that I want to train this model with my own custom dataset. I am wondering if you can provide some tutorials about this? I appreciate it really much.

**Comment by amorehead** [comment]
Hi, @yiyanliao. I have not yet had a chance to put together a formal tutorial on adding new datasets, but I am curious if @peonycabbage has any insights to share after implementing their own new dataset.
